sudo: required

services:
  - docker
  
language: node_js

node_js:
  - "node"
  
before_install:
  - npm install -g gulp
  - npm install

install:
  - gulp 
  
script:
  - true
  #- gulp build.debug
  #- docker run -d --name paella-test-nginx -v `pwd`/build:/usr/share/nginx/html:ro nginx:alpine
  #- docker run -d --name paella-test-selenium --link paella-test-nginx:paella -p 4444:4444 selenium/standalone-chrome:3.3.0
  #- gulp test:local


before_deploy:
  - export PRERELEASE=$(bash ./.publish_scripts/is_prerelease_version.sh ${TRAVIS_TAG})


deploy:
  - provider: script
    script: sh ./.publish_scripts/publish.sh
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: UI6zIHGkhy7p/OtViLbi1yxuyYPteAoRGFO7D8xhc8N6YAkzxYFmlTHdUQgFj4Hgh+5gO6/jW9kpTkbkbATSIVLOLcuLyJEq6jDuorM2q8D2VInpc5ZpNddFjiQdKaIkZL8CeBnncKvmxCBZeHgE4MQPOGHtCQ900viROEVY0ak=
    file:
      - ${HOME}/prebuilt/paella-prebuilt-${TRAVIS_TAG}.tar.gz
    prerelease: ${PRERELEASE}
    on:
      repo: polimediaupv/paella
      tags: true
